# Generated by Django 5.1.3 on 2025-10-29 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CaptchaType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type_name", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True)),
                ("config_json", models.JSONField(blank=True, default=dict)),
                ("image_path", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "verbose_name": "Captcha Type",
                "verbose_name_plural": "Captcha Types",
                "db_table": "captcha_types",
            },
        ),
        migrations.CreateModel(
            name="SceneImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=50)),
                ("file_path", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Scene Image",
                "verbose_name_plural": "Scene Images",
                "db_table": "images",
            },
        ),
        migrations.CreateModel(
            name="CaptchaLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("captcha_type", models.CharField(max_length=50)),
                ("ip", models.GenericIPAddressField(null=True, unpack_ipv4=True)),
                ("access_time", models.DateTimeField(auto_now_add=True)),
                (
                    "result",
                    models.CharField(
                        choices=[("success", "成功"), ("failed", "失败")], max_length=20
                    ),
                ),
                ("message", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Captcha Log",
                "verbose_name_plural": "Captcha Logs",
                "db_table": "captcha_logs",
                "ordering": ["-access_time"],
            },
        ),
    ]
